### ISSUE TITLE
Undefined instance shortly after initialization?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitsharesjs#115]
I'm suddenly getting the following error and I'm struggling to debug it, anyone run into this before?

```
TypeError: Cannot read properties of undefined (reading 'exec')
    at TransactionBuilder2.update_head_block (TransactionBuilder.js:318:48)
```

Triggering from: https://github.com/BTS-CM/airdrop_tool/blob/develop/src/pages/Create.jsx#LL101C29-L101C30

Fails here: https://github.com/BTS-CM/airdrop_tool/blob/develop/src/lib/generate.js#L53

example generate deeplink inputs:
```
{
    "chain": "BTS",
    "node": "wss://node.xbts.io/ws",
    "opType": "ticket_create",
    "opContents": {
        "account": "1.2.5",
        "target_type": 1,
        "amount": {
            "amount": 100000,
            "asset_id": "1.3.0"
        },
        "extensions": [],
        "fee": {
            "amount": 0,
            "asset_id": 0
        }
    }
}
```

Works here: https://github.com/BTS-CM/airdrop_tool/blob/main/src/pages/Create.jsx#L131 (Main branch)

Also works here: https://github.com/BTS-CM/beet-deeplinks/blob/main/examples/BTS/057_ticket_create.js

Would appreciate any help on this, once this error is resolved I'll be translating the locale strings and creating a new release with new features and additional locales. I wasn't expecting this to stop working..

**Comment by grctest** [comment]
Attempting to change the instance code to the following in line with bitsharesjs-ws readme example:

```
  return Apis.instance(
    node,
    true,
    10000,
    { enableCrypto: false, enableOrders: true },
    (error) => console.log(error),
  ).init_promise.then(async (res) => {
    console.log("connected to:", res[0].network);
    const tr = new TXBuilder();
    tr.add_type_operation(opType, opContents);

    try {
      await tr.update_head_block();
    } catch (error) {
      console.error(error);
      return;
    }

    try {
      await tr.set_required_fees();
    } catch (error) {
      console.error(error);
      return;
    }

    try {
      tr.set_expire_seconds(7200);
    } catch (error) {
      console.error(error);
      return;
    }

    try {
      tr.add_signer("inject_wif");
    } catch (error) {
      console.error(error);
      return;
    }

    try {
      tr.finalize();
    } catch (error) {
      console.error(error);
      return;
    }

    let encryptedPayload;
    try {
      encryptedPayload = await tr.encrypt();
    } catch (error) {
      console.error(error);
      return;
    }

    return encryptedPayload;
  }).catch((error) => {
    console.log(error);
  });
```

This ensures the instance connection, however I'm still getting the error:

```
connected to: 
{
    "core_asset": "BTS",
    "address_prefix": "BTS",
    "chain_id": "4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8"
}
TypeError: Cannot read properties of undefined (reading 'exec')
    at TransactionBuilder2.update_head_block (TransactionBuilder.js:318:48)
    at generate.js?t=1686013632315:49:16
    at async fetchData (Create.jsx:114:19)
```

**Comment by grctest** [comment]
turns out wrapping the whole function in a promise fixed it 🤷‍♂️

**Comment by grctest** [comment]
I wrapped the function in a promise and downgraded the library from the develop branch to using the ^6.0.0 main release.

Perhaps there's something in the develop branch causing this issue?
