### ISSUE TITLE
Can't decode memo.

### ISSUE THREAD

**Issue by Rishi556** [bitshares/bitsharesjs#27]
When I try and decode a memo, I get: 

```
/Users/username/Desktop/MD/node_modules/bitsharesjs/dist/ecc/src/PrivateKey.js:130
        var KB = public_key.toUncompressed().toBuffer();
                            ^

TypeError: Cannot read property 'toUncompressed' of null
    at PrivateKey.get_shared_secret (/Users/username/Desktop/MD/node_modules/bitsharesjs/dist/ecc/src/PrivateKey.js:130:29)
    at Function.decrypt_with_checksum (/Users/username/Desktop/MD/node_modules/bitsharesjs/dist/ecc/src/aes.js:97:29)
    at Object.<anonymous> (/Users/username/Desktop/MD/index.js:50:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

**Comment by svk31** [comment]
I'm guessing the root cause was this:
```
AssertionError [ERR_ASSERTION]: Expecting key to begin with GPH, instead got BTS
    at Function.fromStringOrThrow (/Users/username/Desktop/MD/node_modules/bitsharesjs/dist/ecc/src/PublicKey.js:132:26)
```

That can be fixed by configuring the ChainConfig to use BTS prefix.

```
var ChainConfig = require("bitsharesjs-ws").ChainConfig;
ChainConfig.setPrefix("BTS");
```
