### ISSUE TITLE
Beet - importing cloud account encounters 'digest method not supported'

### ISSUE THREAD

**Issue by grctest** [bitshares/bitsharesjs#92]
BlockchainAPI.js:334 Error: Digest method not supported
    at new Hash (node:internal/crypto/hash:67:19)
    at createHash (node:crypto:130:10)
    at ripemd160 (C:\Users\username\Desktop\git\beet\node_modules\bitsharesjs\dist\ecc\src\hash.js:47:37)
    at PublicKey.toPublicKeyString (C:\Users\username\Desktop\git\beet\node_modules\bitsharesjs\dist\ecc\src\PublicKey.js:96:40)
    at PublicKey.toString (C:\Users\username\Desktop\git\beet\node_modules\bitsharesjs\dist\ecc\src\PublicKey.js:82:17)
    at BitShares.getPublicKey (BitShares.js:205:14)
    at BlockchainAPI.js:332:38
    at Array.forEach (<anonymous>)
    at BitShares._callee$ (BlockchainAPI.js:322:31)
    at tryCatch (C:\Users\username\Desktop\git\beet\node_modules\regenerator-runtime\runtime.js:63:40)
ImportCloudPass.vue:69 

{key: 'invalid_key_error'}

Have newer versions of node dropped support for ripemd160?

**Comment by grctest** [comment]
Found a related patch from EOS:
https://github.com/EOSIO/eosjs-ecc/commit/1014cb74f9ebe8ebd48318720a1e8208c5a2f495

**Comment by abitmore** [comment]
Fixed by #93?

**Comment by grctest** [comment]
Yeah this is now fixed, thanks! 👍
